version: '3.7'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mtsds
      MYSQL_ROOT_PASSWORD: mtsds
    volumes:
      - microservices-mtds:/var/lib/mysql
    networks:
      - spring-mysql
    container_name: mysql-container

networks:
  spring-mysql:
    name: mysql-network

volumes:
  microservices-mtds:
