apiVersion: v1
kind: Pod
metadata:
  name: sql
  labels:
    app: sql
spec:
  containers:
  - image: mysql
    name: sql
    env:
    - name: MYSQL_USER
      value: mtsds
    - name: MYSQL_PASSWORD
      value: mtsds
    - name: MYSQL_ROOT_PASSWORD
      value: root
    - name: MYSQL_DATABASE
      value: productdb
    - name: MYSQL_DATABASE
      value: cartdb
    - name: MYSQL_DATABASE
      value: orderdb

---
kind: Service
apiVersion: v1
metadata:
  name: mysql-container
spec:
  selector:
    app: sql
  ports:
  - port: 3306
  type: ClusterIP

---
kind: Service
apiVersion: v1
metadata:
  name: mysql-ext
spec:
  selector:
    app: sql
  ports:
    - name: http
      protocol: TCP
      port: 3306
      nodePort: 30306
  type: NodePort
